### ISSUE TITLE
Figure out where to go in future

### ISSUE THREAD

**Issue by smolck** [smolck/veonim#8]
@breja I’d really like to continue this project (Veonim is cool and I don’t want it to die), but before I start working hard on a fork I’d like to ask you on your thoughts. I’m happy to develop on the original project if given access, but if you’d rather not do that then that’s fine too of course. I just want to contact you about it first and see what you want me to do, if anything specific, and if you’d be comfortable letting me work on the original repo.

**Comment by maxdevjs** [comment]
Is [veonim/veonim](https://github.com/veonim/veonim) archived now?

**Comment by smolck** [comment]
@maxdevjs Yes.

**Comment by smolck** [comment]
I'm going to close this now; I've decided to create [a new repo](https://github.com/smolck/uivonim) for this project, which I think makes sense given that the goals will be fairly different from those of Veonim, at least with regard to VSCode extensions.
